#!/bin/sh
# This script copies jar into a new file along with its size prepended and
# separated by a '\n' as expected by the SVM.

if [ $# -ne 1 -a $# -ne 2 ]; then
  echo "Usage: $0 <jarfile> [ <outfile (default=<jarfile>.flash)> ]";
  exit 1;
fi

if [ $# -eq 2 ]; then
  OUT_FILE=$2
else
  OUT_FILE=$1.flash
fi

JAR_FILE=$1
SIZE=`wc -c $1 | awk '{print \$1}'`
echo $SIZE > $OUT_FILE
cat $JAR_FILE >> $OUT_FILE
echo "Output is in '$OUT_FILE'"
