/*
 *	Header File	: noisesrc.h
 *	Original Author	: K H Ong
 *	Created		: 16 Aug 2000
 *
 * Copyright 2000 D'Crypt Pte Ltd
 * All rights reserved.
 *
 * This file provides the function prototypes for accessing the noise source.
 *
 * $Id: noisesrc.h,v 1.1.1.1 2002/05/21 20:38:47 dougxc Exp $
 *
 */
#ifndef _NOISESRC_H
#define _NOISESRC_H

#include "dcrypt_global.h"

/* 
 * Initialize the noise source.  Should be called once before any other ns 
 * function.
 */
extern void 	ns_init(void) ;

/*
 * Get a random bit from the noise source.
 */
extern int	ns_get_bit(void) ;

/*
 * Get a random byte from the noise source. The random byte will be stored in 
 * the lowest 8 bits of the returned data with bit 0 being the latest random 
 * bit and bit 7 the oldest random bit.
 */
extern int	ns_get_byte(void) ;

/* 
 * Perform FIPS tests on the noise source. Return OK only if the random bits 
 * generated by the noise source passed ALL the 4 FIPS tests, otherwise ERROR 
 * is returned.
 */
extern RESULT	ns_fips_tests() ;

#endif
